"""add user table

Revision ID: 8081b29d2b20
Revises: fd470c3ddd8a
Create Date: 2026-06-05 05:32:18.807009

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8081b29d2b20'
down_revision = 'fd470c3ddd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('provider', sa.Enum('microsoft', 'google', name='userprovider'), nullable=True),
    sa.Column('profile_pic_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column(
        'profile_type',
        sa.Enum('child', 'guest', 'default', name='userprofiletype'),
        nullable=False,
    ),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_deactivated', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('entities', 'enum_field',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='enum'),
               type_=sa.Enum('A', 'B', 'C', 'D', name='entityenum'),
               nullable=True)
    op.alter_column('entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.add_column('simple_entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('simple_entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('simple_entities', 'enum_field',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='simple_entity_enum'),
               type_=sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'),
               nullable=True)
    op.alter_column('simple_entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simple_entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('simple_entities', 'enum_field',
               existing_type=sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', name='simple_entity_enum'),
               nullable=False)
    op.drop_column('simple_entities', 'updated_at')
    op.drop_column('simple_entities', 'created_at')
    op.alter_column('entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('entities', 'enum_field',
               existing_type=sa.Enum('A', 'B', 'C', 'D', name='entityenum'),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', name='enum'),
               nullable=False)
    op.drop_column('entities', 'updated_at')
    op.drop_column('entities', 'created_at')
    op.drop_table('users')
    # ### end Alembic commands ###
