"""add event series table to track event recurrence

Revision ID: ade5c04e9b79
Revises: 0746657dd317
Create Date: 2026-07-17 02:28:47.983607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ade5c04e9b79'
down_revision = '0746657dd317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_series',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('max_attendees', sa.Integer(), nullable=False),
    sa.Column('max_waitlist', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Uuid(), nullable=True),
    sa.Column('event_status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('signup_start_time', sa.DateTime(), nullable=False),
    sa.Column('signup_end_time', sa.DateTime(), nullable=False),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('format', sa.Enum('signup', 'dropin', name='eventformatenum'), nullable=False),
    sa.Column('registration_type', sa.Enum('lottery', 'auto_approve', 'manual_approve', name='eventregistrationtypeenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('entities', 'enum_field',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='enum'),
               type_=sa.Enum('A', 'B', 'C', 'D', name='entityenum'),
               nullable=True)
    op.alter_column('entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.add_column('events', sa.Column('event_type_id', sa.Uuid(), nullable=True))
    op.add_column('events', sa.Column('event_series_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('events_event_type_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'event_types', ['event_type_id'], ['id'])
    op.create_foreign_key(None, 'events', 'event_series', ['event_series_id'], ['id'])
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'recurrence')
    op.add_column('simple_entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('simple_entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('simple_entities', 'enum_field',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='simple_entity_enum'),
               type_=sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'),
               nullable=True)
    op.alter_column('simple_entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simple_entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('simple_entities', 'enum_field',
               existing_type=sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', name='simple_entity_enum'),
               nullable=False)
    op.drop_column('simple_entities', 'updated_at')
    op.drop_column('simple_entities', 'created_at')
    op.add_column('events', sa.Column('recurrence', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('event_type', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_event_type_fkey'), 'events', 'event_types', ['event_type'], ['id'])
    op.drop_column('events', 'event_series_id')
    op.drop_column('events', 'event_type_id')
    op.alter_column('entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('entities', 'enum_field',
               existing_type=sa.Enum('A', 'B', 'C', 'D', name='entityenum'),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', name='enum'),
               nullable=False)
    op.drop_column('entities', 'updated_at')
    op.drop_column('entities', 'created_at')
    op.drop_table('event_series')
    # ### end Alembic commands ###
