"""add unique constraint on event_types.name

Revision ID: b2c0597042a8
Revises: 0746657dd317
Create Date: 2026-07-07 01:50:10.207114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c0597042a8'
down_revision = '0746657dd317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_event_types_name', 'event_types', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_event_types_name', 'event_types', type_='unique')
    # ### end Alembic commands ###
