"""add unique constraint on event_types.name

Revision ID: b2c0597042a8
Revises: 0746657dd317
Create Date: 2026-07-07 01:50:10.207114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c0597042a8'
down_revision = '0746657dd317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('entities', 'enum_field',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='enum'),
               type_=sa.Enum('A', 'B', 'C', 'D', name='entityenum'),
               nullable=True)
    op.alter_column('entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.create_unique_constraint('uq_event_types_name', 'event_types', ['name'])
    op.add_column('simple_entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('simple_entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('simple_entities', 'enum_field',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='simple_entity_enum'),
               type_=sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'),
               nullable=True)
    op.alter_column('simple_entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simple_entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('simple_entities', 'enum_field',
               existing_type=sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', name='simple_entity_enum'),
               nullable=False)
    op.drop_column('simple_entities', 'updated_at')
    op.drop_column('simple_entities', 'created_at')
    op.drop_constraint('uq_event_types_name', 'event_types', type_='unique')
    op.alter_column('entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('entities', 'enum_field',
               existing_type=sa.Enum('A', 'B', 'C', 'D', name='entityenum'),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', name='enum'),
               nullable=False)
    op.drop_column('entities', 'updated_at')
    op.drop_column('entities', 'created_at')
    # ### end Alembic commands ###
