"""Update app.models.events to track recurrence through event_series_id

Revision ID: e4694403085d
Revises: b945a06e4bdd
Create Date: 2026-06-27 20:40:02.578382

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4694403085d'
down_revision = 'b945a06e4bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_series',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('entities', 'enum_field',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='enum'),
               type_=sa.Enum('A', 'B', 'C', 'D', name='entityenum'),
               nullable=True)
    op.alter_column('entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.add_column('events', sa.Column('event_type_id', sa.Uuid(), nullable=True))
    op.add_column('events', sa.Column('event_series_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('events_event_type_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key('events_event_type_id_fkey', 'events', 'event_types', ['event_type_id'], ['id'])
    op.create_foreign_key('events_event_series_id_fkey', 'events', 'event_series', ['event_series_id'], ['id'])
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'recurrence')
    op.add_column('simple_entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('simple_entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('simple_entities', 'enum_field',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='simple_entity_enum'),
               type_=sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'),
               nullable=True)
    op.alter_column('simple_entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simple_entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('simple_entities', 'enum_field',
               existing_type=sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', name='simple_entity_enum'),
               nullable=False)
    op.drop_column('simple_entities', 'updated_at')
    op.drop_column('simple_entities', 'created_at')
    op.add_column('events', sa.Column('recurrence', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('event_type', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('events_event_series_id_fkey', 'events', type_='foreignkey')
    op.drop_constraint('events_event_type_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_event_type_fkey'), 'events', 'event_types', ['event_type'], ['id'])
    op.drop_column('events', 'event_series_id')
    op.drop_column('events', 'event_type_id')
    op.alter_column('entities', 'string_array_field',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('entities', 'enum_field',
               existing_type=sa.Enum('A', 'B', 'C', 'D', name='entityenum'),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', name='enum'),
               nullable=False)
    op.drop_column('entities', 'updated_at')
    op.drop_column('entities', 'created_at')
    op.drop_table('event_series')
    # ### end Alembic commands ###
